<script id="tmpl-homepage" type="text/html">
	<md-content layout-padding>
		<div class="content-container">
			<h2 class="md-headline">What is Phalcon VM?</h2>

			<p>
				Phalcon VM is an open source Vagrant configuration focused on PHP development. This
				configuration, like a Swiss army knife, contains lots of services required for modern
				development and allows you to activate and use only those which are needed for your projects.
			</p>

			<p>
				Currently Phalcon VM contains 10 additional services apart Nginx and PHP. It is <b>Varnish</b>
				cache, <b>MySQL</b>, <b>PostgreSQL</b> and <b>MongoDB</b> databases, <b>Redis</b> and
				<b>Memcached</b> caching systems, <b>Gearman</b> and <b>RabbitMQ</b> queue systems, <b>Sphinx</b>
				and <b>Elasticsearch</b> search engines.
			</p>

			<br>

			<h2 class="md-headline">Want to contribute?</h2>

			<p>
				The best place to start is to open <a href="https://github.com/eugene-manuilov/phalcon-vm/issues/new">a new ticket</a>
				on github and describe what you want to improve or fix. It is important to start from a dialog, because it can reveal
				hidden possibilities or potential pitfalls which might be oversight.
			</p>

			<p>
				Of course, if you think that your contribution will be definitely needed and you know
				what you are doing, then you can fork the repository and create a new branch which
				has self-explanatory name. Implement your changes or fixes, commit it into your branch
				and push it to the github. Once you do it you can create a pull request where you need
				to explain what you have done.
			</p>

			<br>

			<h2 class="md-headline">License information</h2>

			<p>
				Phalcon VM is licensed under The MIT License (MIT). Which means that you can use, copy,
				modify, merge, publish, distribute, sublicense, and/or sell copies of the Software.
				But you always need to state the original author of this configuration.
			</p>
		</div>
	</md-content>
</script>