<script id="tmpl-new-site" type="text/html">
	<div class="dialog-container">
		<form name="siteForm">
			<md-input-container class="md-block">
				<label>Site Name</label>
				<input type="text" name="label" ng-model="site.data.label" md-autofocus md-no-asterisk required>
				<div ng-messages="siteForm.label.$error">
					<div ng-message="required">This field is required.</div>
				</div>
			</md-input-container>

			<md-input-container class="md-block">
				<label>Directory</label>
				<input type="text" name="direcotry" ng-model="site.data.directory" md-no-asterisk required>
				<div ng-messages="siteForm.direcotry.$error">
					<div ng-message="required">This field is required.</div>
				</div>
			</md-input-container>

			<md-input-container class="md-block">
				<label>Domains (space-separated)</label>
				<input type="text" name="domains" ng-model="site.data.domains" md-no-asterisk required>
				<div ng-messages="siteForm.domains.$error">
					<div ng-message="required">This field is required.</div>
				</div>
			</md-input-container>

			<md-input-container class="md-block">
				<label>Repository</label>
				<input type="text" name="repository" ng-model="site.data.repository">
			</md-input-container>

			<md-input-container class="md-block">
				<label>Repository Provider</label>
				<md-select ng-model="site.data.provider">
					<md-option ng-repeat="pvd in site.providers" ng-value="pvd.key">
						{{pvd.label}}
					</md-option>
				</md-select>
			</md-input-container>

			<div class="dialog-actions" layout="row">
				<md-button class="md-warn" ng-click="site.cancel()">Cancel</md-button>
				<span flex></span>
				<md-button class="md-primary" ng-click="site.add()">Add</md-button>
			</div>
		</form>
	</div>
</script>
