<script id="tmpl-new-site" type="text/html">
	<md-content layout-padding>
		<div class="content-container">
			<form name="siteForm">
				<md-input-container class="md-block">
					<label>Site Name</label>
					<input type="text" name="name" ng-model="site.name" md-no-asterisk required>
					<div ng-messages="siteForm.name.$error">
						<div ng-message="required">This field is required.</div>
					</div>
				</md-input-container>

				<md-input-container class="md-block">
					<label>Directory</label>
					<input type="text" name="direcotry" ng-model="site.directory" md-no-asterisk required>
					<div ng-messages="siteForm.direcotry.$error">
						<div ng-message="required">This field is required.</div>
					</div>
				</md-input-container>

				<div layout-gt-sm="row">
					<md-input-container class="md-block" flex-gt-sm>
						<label>Repository</label>
						<input ng-model="site.repository">
					</md-input-container>

					<md-input-container class="md-block" flex-gt-sm>
						<label>Repository Provider</label>
						<md-select ng-model="site.provider">
							<md-option ng-repeat="pvd in site.providers" ng-value="pvd.key">
								{{pvd.label}}
							</md-option>
						</md-select>
					</md-input-container>
				</div>

				<div>
					<md-button type="submit">Save</md-button>
				</div>
			</form>
		</div>
	</md-content>
</script>