<?php

foreach ( $groups as $group => $groupData ) :

	?><script id="tmpl-<?php echo $group; ?>" type="text/html">
		<div class="content-container">
			<header class="header">
				<h2 class="md-display-1"><?php echo $groupData['label']; ?></h2>
			</header><?php

			if ( is_array( $groupData['description'] ) ) :
				?><p><?php echo implode( '</p><p>', $groupData['description'] ); ?></p><?php
			else :
				?><p><?php echo $groupData['description']; ?></p><?php
			endif;

			if ( count( $groupData['tabs'] ) > 1 ) :
				?><md-tabs md-stretch-tabs="auto" md-dynamic-height="true">
					<?php foreach ( $groupData['tabs'] as $tab => $tabData ) : ?>
						<md-tab label="<?php echo $tab; ?>">
							<md-tab-body><?php
								$this->partial( "index/_list", array(
									'key'    => $tabData['key'],
									'fields' => $tabData['fields'],
								) );
							?></md-tab-body>
						</md-tab>
					<?php endforeach; ?>
				</md-tabs><?php
			else :
				foreach ( $groupData['tabs'] as $tab => $tabData ) :
					$this->partial( "index/_list", array(
						'key'    => $tabData['key'],
						'fields' => $tabData['fields'],
					) );
				endforeach;
			endif;
		?></div>
	</script><?php

endforeach;