<?php

foreach ( $phalconvm['menu']['environment'] as $env ) :
	?><script id="tmpl-<?php echo $env['key']; ?>" type="text/html">
		<div class="content-container">
			<header class="header">
				<h2 class="md-display-1"><?php echo $env['label']; ?></h2>
			</header>

			<md-tabs md-stretch-tabs="auto" md-dynamic-height="true">
				<?php foreach ( $env['items'] as $tab => $tabLabel ) : ?>
					<md-tab label="<?php echo $tabLabel; ?>">
						<md-tab-body><?php

							foreach ( $phalconvm['fields'][ $tab ] as $blockLabel => $tabData ) :
								?><h2 class="md-subhead"><?php echo $blockLabel; ?></h2><?php

								$this->partial( "index/_list", array(
									'key'    => $tabData['key'],
									'fields' => $tabData['fields'],
								) );
							endforeach;
						?></md-tab-body>
					</md-tab>
				<?php endforeach; ?>
			</md-tabs>
		</div>
	</script><?php
endforeach;