<p>
	Elasticsearch is a search engine based on Lucene. It provides a distributed,
	multitenant-capable full-text search engine with an HTTP web interface and
	schema-free JSON documents.
</p>

<div md-whiteframe="-1">
	<md-list>
		<md-list-item class="md-2-line">
			<md-switch class="md-secondary"></md-switch>
			<div class="md-list-item-text">
				<h3>Enabled</h3>
				<p>You can turn on or off the service.</p>
			</div>
		</md-list-item>
	</md-list>
</div>