<p>
	Gearman provides a generic application framework to farm out work to other machines
	or processes that are better suited to do the work. It allows you to do work in
	parallel, to load balance processing, and to call functions between languages.
	It can be used in a variety of applications, from high-availability web sites
	to the transport of database replication events. In other words, it is the nervous
	system for how distributed processing communicates.
</p>

<md-list>
	<md-list-item class="md-2-line">
		<md-switch class="md-secondary"></md-switch>
		<div class="md-list-item-text">
			<h3>Enabled</h3>
			<p>You can turn on or off the service.</p>
		</div>
	</md-list-item>
</md-list>