<p>
	Memcached is an in-memory key-value store for small chunks of arbitrary data
	(strings, objects) from results of database calls, API calls, or page rendering.
</p>

<md-tabs md-stretch-tabs="auto" md-dynamic-height="true">
	<md-tab label="Memcache server">
		<md-tab-body>
			<md-list>
				<md-divider></md-divider>
				<md-list-item class="md-2-line">
					<md-switch class="md-secondary" ng-model="data.service.Enabled" ng-change="app.setNasty()"></md-switch>
					<div class="md-list-item-text">
						<h3>Enabled</h3>
						<p>Defines whether Memcache should be activated on provision or disabled.</p>
					</div>
				</md-list-item>
				<md-divider></md-divider>
			</md-list>
		</md-tab-body>
	</md-tab>

	<md-tab label="phpMemcacheAdmin">
		<md-tab-body>
			<md-list>
				<md-divider></md-divider>
				<md-list-item class="md-2-line">
					<md-switch class="md-secondary" ng-model="data.phpMemcacheAdmin.Enabled" ng-change="app.setNasty()"></md-switch>
					<div class="md-list-item-text">
						<h3>Enabled</h3>
						<p>Defines whether phpMemcacheAdmin should be activated on provision or disabled.</p>
					</div>
				</md-list-item>
				<md-divider></md-divider>
			</md-list>
		</md-tab-body>
	</md-tab>
</md-tabs>