<p>
	Memcached is an in-memory key-value store for small chunks of arbitrary data
	(strings, objects) from results of database calls, API calls, or page rendering.
</p>

<div md-whiteframe="-1">
	<md-list>
		<md-list-item class="md-2-line">
			<md-switch class="md-secondary"></md-switch>
			<div class="md-list-item-text">
				<h3>Enabled</h3>
				<p>You can turn on or off the service.</p>
			</div>
		</md-list-item>
	</md-list>
</div>