<p>
	MongoDB is a free and open-source cross-platform document-oriented database program.
	Classified as a NoSQL database program, MongoDB avoids the traditional table-based
	relational database structure in favor of JSON-like documents with dynamic schemas
	(It calls the format BSON), making the integration of data in certain types of
	applications easier and faster.
</p>

<md-list>
	<md-list-item class="md-2-line">
		<md-switch class="md-secondary"></md-switch>
		<div class="md-list-item-text">
			<h3>Enabled</h3>
			<p>You can turn on or off the service.</p>
		</div>
	</md-list-item>
</md-list>