<p>
	NGINX is a free, open-source, high-performance HTTP server and reverse proxy,
	as well as an IMAP/POP3 proxy server. NGINX is known for its high performance,
	stability, rich feature set, simple configuration, and low resource consumption.
</p>

<md-list>
	<md-list-item class="md-2-line">
		<md-switch class="md-secondary"></md-switch>
		<div class="md-list-item-text">
			<h3>Enabled</h3>
			<p>You can turn on or off the service.</p>
		</div>
	</md-list-item>
</md-list>