<p>
	PostgreSQL, often simply Postgres, is an object-relational database, with additional
	"object" features – with an emphasis on extensibility and standards-compliance.
	As a database server, its primary function is to store data securely, and to allow
	for retrieval at the request of other software applications. It can handle workloads
	ranging from small single-machine applications to large Internet-facing applications
	with many concurrent users.
</p>

<div md-whiteframe="-1">
	<md-list>
		<md-list-item class="md-2-line">
			<md-switch class="md-secondary"></md-switch>
			<div class="md-list-item-text">
				<h3>Enabled</h3>
				<p>You can turn on or off the service.</p>
			</div>
		</md-list-item>
	</md-list>
</div>