<p>
	RabbitMQ is open source message broker software that implements the Advanced
	Message Queuing Protocol (AMQP). The RabbitMQ server is written in the Erlang
	programming language and is built on the Open Telecom Platform framework for
	clustering and failover. Client libraries to interface with the broker are
	available for all major programming languages.
</p>

<div md-whiteframe="-1">
	<md-list>
		<md-list-item class="md-2-line">
			<md-switch class="md-secondary"></md-switch>
			<div class="md-list-item-text">
				<h3>Enabled</h3>
				<p>You can turn on or off the service.</p>
			</div>
		</md-list-item>
	</md-list>
</div>