<p>
	Redis is an open source (BSD licensed), in-memory data structure store, used
	as database, cache and message broker. It supports data structures such as strings,
	hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and
	geospatial indexes with radius queries. Redis has built-in replication, Lua
	scripting, LRU eviction, transactions and different levels of on-disk persistence,
	and provides high availability via Redis Sentinel and automatic partitioning
	with Redis Cluster.
</p>

<div md-whiteframe="-1">
	<md-list>
		<md-list-item class="md-2-line">
			<md-switch class="md-secondary"></md-switch>
			<div class="md-list-item-text">
				<h3>Enabled</h3>
				<p>You can turn on or off the service.</p>
			</div>
		</md-list-item>
	</md-list>
</div>