<p>
	Sphinx is an open source full text search server, designed from the ground up
	with performance, relevance (aka search quality), and integration simplicity
	in mind.
</p>

<md-list>
	<md-list-item class="md-2-line">
		<md-switch class="md-secondary"></md-switch>
		<div class="md-list-item-text">
			<h3>Enabled</h3>
			<p>You can turn on or off the service.</p>
		</div>
	</md-list-item>
</md-list>