<md-sidenav id="sidebar" class="md-sidenav-left" md-component-id="left" md-is-locked-open="$mdMedia('gt-sm')" md-whiteframe="4">
	<header class="nav-header" layout-padding>
		<h1 id="logo" class="md-heading">
			<a href="/">PhalconVM</a>
		</h1>
	</header>

	<md-divider></md-divider>

	<md-content id="sidebar-menu">
		<div ng-repeat="(label, group) in app.menu">
			<span class="section-title">{{label}}</span>
			<ul>
				<li class="menu-item" ng-repeat="(key, item) in group">
					<a ng-href="{{key}}">
						<i class="material-icons" ng-show="item.icon">{{item.icon}}</i> {{item.label}}
					</a>
				</li>
			</ul>

			<md-divider ng-hide="$last"></md-divider>
		</div>
	</md-content>
</md-sidenav>

<div id="wrapper" layout="column" flex>
	<md-toolbar id="toolbar">
		<div class="md-toolbar-tools">
			<md-button class="md-icon-button" ng-click="app.toggleSidenav()" hide-gt-sm>
				<i class="material-icons">menu</i>
			</md-button>

			<h2 class="md-toolbar-item md-breadcrumb md-headline" ng-show="$root.title">
				<span class="md-breadcrumb-page">{{$root.title}}</span>
			</h2>

			<span flex></span>

			<md-button class="md-primary" ng-disabled="!app.nasty" ng-click="app.saveChanges()" ng-show="$root.saveButton">
				Save Changes
			</md-button>
		</div>
	</md-toolbar>

	<div id="content" ng-view></div>
</div>

<?php echo $this->getContent(); ?>