<md-sidenav id="sidebar" class="md-sidenav-left" md-component-id="left" md-is-locked-open="$mdMedia('gt-sm')" md-whiteframe="4">
	<header class="nav-header" layout-padding>
		<h1 id="logo" class="md-heading">
			<a href="/">PhalconVM</a>
		</h1>
	</header>

	<md-divider></md-divider>

	<md-content id="sidebar-menu">
		<div ng-repeat="(label, block) in app.menu">
			<span class="section-title">{{label}}</span>
			<ul>
				<li>
					<ul>
						<li class="menu-item" ng-repeat="(key, group) in block">
							<a ng-href="{{key}}">{{group.label}}</a>
						</li>
					</ul>
				</li>
			</ul>

			<md-divider ng-hide="$last"></md-divider>
		</div>
	</md-content>
</md-sidenav>

<div id="wrapper" layout="column" flex>
	<md-toolbar id="toolbar">
		<div class="md-toolbar-tools">
			<md-button class="md-icon-button" ng-click="app.toggleSidenav()" hide-gt-sm>
				<md-icon md-svg-src="/svg/ic_menu_black_24px.svg" aria-label="menu" style="color:white"></md-icon>
			</md-button>

			<h2 class="md-toolbar-item md-breadcrumb md-headline" ng-show="$root.title">
				<span class="md-breadcrumb-page">{{$root.title}}</span>
			</h2>

			<span flex></span>

			<md-button class="md-primary" ng-disabled="!app.nasty" ng-click="app.saveChanges()" ng-show="$root.saveButton">
				Save Changes
			</md-button>
		</div>
	</md-toolbar>

	<div id="content" ng-view></div>
</div>

<?php echo $this->getContent(); ?>

<script id="tmpl-homepage" type="text/html">
	<div class="content-container">
		<h2 class="md-headline">Welcome to <b>Phalcon VM</b>!</h2>

		<p>
			Phalcon VM is an open source Vagrant configuration focused on PHP development. This
			configuration, like a Swiss army knife, contains lots of tools required for modern
			development and allows you to activate and use only those tools which are needed
			for your project.
		</p>

		<h3>Want to contribute?</h3>

		<p>
			The best place to start is to open a new ticket on github and describe what you want
			to improve or fix. It is important to start from a dialog, because it can reveal hidden
			possibilities or potential pitfalls which might be oversight.
		</p>

		<p>
			Of course, if you think that your contribution will be definitely needed and you know
			what you are doing, then you can fork the repository and create a new branch which
			has self-explanatory name. Implement your changes or fixes, commit it into your branch
			and push it to the github. Once you do it you can create a pull request where you need
			to explain what you have done.
		</p>

		<h3>License information</h3>

		<p>
			Phalcon VM is licensed under The MIT License (MIT). Which means that you can use, copy,
			modify, merge, publish, distribute, sublicense, and/or sell copies of the Software.
			But you always need to state the original author of this configuration.
		</p>
	</div>
</script>